- name: Ansible Copy Local to Remote
  hosts: "{{hosts}}"
  vars:
    src_path: "{{ workspace_path }}/"
    dest_path: "/home/ansadmin"
    config_file_dest_path: "/home"
  tasks:
    - name: copying files with playbook
      become: true
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: ansadmin
        group: ansadmin
        mode: 0777
    - name: echo path
      shell:
        cmd: export PATH=$PATH:/usr/local/bin
    - name: create frontend
      shell:
        cmd: kubectl apply -f frontend.yaml
    - name: create backend
      shell:
        cmd: kubectl apply -f backend.yaml
    - name: create database
      shell:
        cmd: kubectl apply -f database.yaml       
    - name: create namespace
      shell:
        cmd: kubectl create namespace monitoring   
    - name: create namespacedaemonset
      shell:
        cmd: kubectl apply -f daemonset.yaml
    - name: create service
      shell:
        cmd: kubectl apply -f service.yaml      

    # - name: build image
    #   become: true
    #   shell:
    #     cmd: ./gradlew jibDockerBuild
    # - name: edit env path 
    #   shell: "export PATH=$PATH:/usr/local/bin"
    # - name: start containers
    #   shell:
    #     cmd: docker-compose up


#try to use execute commands over ssh instead...

#  add this command to edit path variable... export PATH=$PATH:/usr/local/bin


    # - name: pull docker image
    #   become: true
    #   shell:
    #     "docker pull joeting91/nuvalence"